name: Containerfile Linter

on:
  push:
    branches:
      - "main"
    paths:
      - ".devcontainer/Containerfile.*"
  pull_request:
    branches:
      - "main"
    paths:
      - ".devcontainer/Containerfile.*"

jobs:
  run-lint:
    name: Hadolint Action
    runs-on: ubuntu-latest
    environment: hadolint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: .devcontainer/Containerfile.${{ secrets.VARIANT }}
