---
name: Super-Linter

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".devcontainer/Containerfile.*"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".devcontainer/Containerfile.*"

jobs:
  run-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          ACTIONS_RUNNER_DEBUG: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_EDITORCONFIG: true
          VALIDATE_GITHUB_ACTIONS: true
